### PR TITLE
Remove unix-specific executor in xtask

### LINKED ISSUE #76: xtask builder is unix-specific, 'cargo xtask build-ebpf' fails on Windows
Due to use of `std::os::unix::process::CommandExt` in https://github.com/aya-rs/aya-template/blob/e86392d422048729799d9da6556c8b798735c474/xtask/src/run.rs#L1 and `CommandExt.exec()` in https://github.com/aya-rs/aya-template/blob/e86392d422048729799d9da6556c8b798735c474/xtask/src/run.rs#L63, `cargo xtask build-ebpf` currently fails on Windows.  There seems to be now compelling reason to use Unix-specific command executor, and generating BPF bytecode should be possible using Windows too.  I think we should change it to the generic command runner https://doc.rust-lang.org/std/process/struct.Command.html#method.status which we already use in `build_ebpf.rs` https://github.com/aya-rs/aya-template/blob/e86392d422048729799d9da6556c8b798735c474/xtask/src/build_ebpf.rs#L56-L60.

### PR DESCRIPTION
**Pull request by dmitris**
Change unix-specific executor to generic one
to enable xtask working on Windows and eventually
be able to cross-compile on Windows.

Fixes #76.

### CODE REVIEW

File: xtask/src/run.rs [hunk 1]
```diff
@@ -57,11 +57,12 @@ pub fn run(opts: Options) -> Result<(), anyhow::Error> {
...
+    // run the command
+    let status = Command::new(args.first().expect("No first argument"))
         .args(args.iter().skip(1))
-        .exec();
+        .status()
+        .expect("failed to run the command");
 
-    // we shouldn't get here unless the command failed to spawn
-    Err(anyhow::Error::from(err).context(format!("Failed to run `{}`", args.join(" "))))
+    assert!(status.success());
```
Comment (vadorovsky) [inline xtask/src/run.rs:66]: I think we should still fail with a descriptive message, not just with an assertion. So something like:

```suggestion
    if !status.success() {
        anyhow::bail!("Failed to run `{}`", args.join(" "));
    }
```

**Review by vadorovsky — CHANGES_REQUESTED** [review]

File: xtask/src/run.rs (hunk 1 above)
Comment (dmitris) [reply xtask/src/run.rs]: then we probably should do the same with `build_ebpf.rs` as well = show the cargo command with arguments when it fails?

**Review by vadorovsky — APPROVED** [review]
